apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
   kubernetes.io/ingress.class: "private-iks-k8s-nginx"
spec:
  rules:
  - host: airflow.map-mktsys-dev.limited-use.ibm.com
    http:
      paths:
      - path: /grafana
        backend:
          serviceName: prometheus-stack-grafana
          servicePort: 3000
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ldap-bind-password
  namespace: monitoring
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true 
  data:
    - key: DEV_LDAP_BIND_PASSWORD
      property: payload
      name: LDAP_BIND_PASSWORD
      secretType: arbitrary
      