kind: ConfigMap
apiVersion: v1
metadata:
  name: query-exporter
  namespace: monitoring
data:
  config.yaml: |
    databases:
      db1:
        dsn: env:DEV_DB2_DSN
        labels:
          region: US
          app: MIP
          environment: DEV 
      db2:
        dsn: env:TEST_DB2_DSN
        labels:
          region: US
          app: MIP
          environment: TEST
      db3:
        dsn: env:PROD_DB2_DSN
        keep-connected: false
        labels:
          region: US
          app: MIP
          environment: PROD

    metrics:
      log_utilization_percent:
        type: gauge
        description: LOG_UTILIZATION_PERCENT
      total_log_used_kb:
        type: gauge
        description: TOTAL_LOG_USED_KB
      total_log_available_kb:
        type: gauge
        description: TOTAL_LOG_AVAILABLE_KB
      total_log_used_top_kb:
        type: gauge
        description: TOTAL_LOG_USED_TOP_KB
      uow_log_space:
        type: gauge
        description: IN_FLIGHT_QUERIES
        labels: [elapsed_time,application_handle]
        expiration: 5m
      total_idm_requests:
        type: gauge
        description: TOTAL_IDM_REQUESTS
      idm_pending_count:
        type: gauge
        description: IDM_PENDING_COUNT
      avg_idm_processing_time:
        type: gauge
        description: AVG_IDM_PROCESSING_TIME
      leads_reg_cnt:
        type: gauge
        description: LEADS_REG_CNT
      leads_imi_cnt:
        type: gauge
        description: LEADS_IMI_CNT
      leads_pers_cnt:
        type: gauge
        description: LEADS_PERS_CNT
      leads_actv_cnt:
        type: gauge
        description: LEADS_ACTV_CNT

    queries:
      query1:
        schedule: "*/1 * * * *"
        databases: [db1,db2]
        metrics: [log_utilization_percent,total_log_used_kb,total_log_available_kb,total_log_used_top_kb]
        sql: |
          SELECT
            LOG_UTILIZATION_PERCENT,
            TOTAL_LOG_USED_KB,
            TOTAL_LOG_AVAILABLE_KB,
            TOTAL_LOG_USED_TOP_KB
          FROM MAP_AUDT.TS_USAGE;
      query2:
        schedule: "*/5 * * * *"
        databases: [db1,db2]
        metrics: [uow_log_space]
        sql: |
          SELECT
            ELAPSED_TIME_SEC AS ELAPSED_TIME,
            APPLICATION_HANDLE AS APPLICATION_HANDLE,
            UOW_LOG_SPACE_USED AS UOW_LOG_SPACE
          FROM MAP_AUDT.IN_FLIGHT_QUERIES;
      query3:
        schedule: "*/30 * * * *"
        databases: [db3]
        metrics: [total_idm_requests,idm_pending_count,avg_idm_processing_time]
        sql: |
          SELECT
              COUNT(1) AS TOTAL_IDM_REQUESTS,
              COUNT (CASE WHEN IDM_PROCESS_STEP IS NULL THEN 1 ELSE NULL END ) AS IDM_PENDING_COUNT,
              AVG (
                CASE WHEN IDM_PROCESS_STEP IN ('Y', 'R')
                    THEN TIMESTAMPDIFF(4, IDM_PROCESS_STEP_UPDATE_TS - CREATE_TS )
                ELSE 0 END
              ) AS AVG_IDM_PROCESSING_TIME
          FROM MAP_IDM.IDM_MAINTAIN_PERSON IMP
          WHERE CREATE_TS >= CURRENT_TIMESTAMP - 30 MINUTES AND SOURCE_PROCESS = 'MAT';
      query4:
        schedule: "*/30 * * * *"
        databases: [db3]
        metrics: [leads_reg_cnt,leads_imi_cnt,leads_pers_cnt,leads_actv_cnt]
        sql: |
          SELECT
              COUNT(RRG.TRANSACTIONID) AS LEADS_REG_CNT,
              COUNT(IMI.REGISTRATION_ID) AS LEADS_IMI_CNT,
              COUNT(P.MIP_SEQ_ID) AS LEADS_PERS_CNT,
              COUNT(A.MIP_ACTIVITY_SEQ_ID) AS LEADS_ACTV_CNT
          FROM
              MAP_CORE.MCT_INBOUND_MARKETING_INTERACTION_MIP IMI
          LEFT JOIN MAP_STG.STG_RAW_REGISTRATION RRG ON
              RRG.TRANSACTIONID = IMI.REGISTRATION_ID
          LEFT JOIN MAP_MKTO.MCT_MKTO_PERSON P ON
              P.MIP_SEQ_ID = IMI.MIP_SEQ_ID AND P.MIP_TRANS_ID = IMI.REGISTRATION_ID
          LEFT JOIN MAP_MKTO.MCV_MKTO_CUSTOM_ACTIVITY A ON
              A.MIP_SEQ_ID = P.MIP_SEQ_ID AND A.MIP_TRANS_ID = P.MIP_TRANS_ID
          WHERE
              IMI.CREATE_TS > CURRENT TIMESTAMP - 30 MINUTES
              AND (IMI.MARKETING_INTERACTION_TYPE_CD = 'MAIL' OR IMI.CLIENT_INTEREST_FLG = 'Y');

